import Head from 'next/head'
import React from 'react'
import PropTypes from 'prop-types'

const _error = ({}) => {
  return (
    <>
      <Head>
        <title>Kenneth Andales | Portfolio Website </title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          type='image/svg+'
          rel='icon'
          href='/icon.svg'
        />
      </Head>
      <main>
        <h1>error 404 not found</h1>
      </main>
    </>
  )
}

_error.propTypes = {}

export default _error
