import Head from 'next/head'
import Header from '@/components/pages/header'
import { PropsWithChildren } from 'react'
import About from '@/components/pages/about'
import Nav from '@/components/layout/nav'
import Skills from '@/components/pages/skills'
import Knowledge from '@/components/pages/knowledge'
import Experience from '@/components/pages/experience'
import Portfolio from '@/components/pages/portfolio'
import Contact from '@/components/pages/contact'
import Footer from '@/components/layout/footer'

type props = PropsWithChildren<{}>

const Home: React.FC<props> = ({}) => {
  return (
    <>
      <Head>
        <title>Kenneth Andales | Portfolio Website</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          type='image/svg+'
          rel='icon'
          href='/icon.svg'
        />
      </Head>
      <main>
        <Nav />
        <Header />
        <About />
        <Skills />
        <Knowledge />
        <Experience />
        <Portfolio />
        <Contact />
        <Footer />
      </main>
    </>
  )
}

export default Home
